from .usuarioRouters import router
from .horarioRouters import horario_router
from .reservaRouters import reserva_router
from .asistenciasyReservasRouters import asistenciasyreservas_router
from .noticiaRouters import noticia_router
from .equipoRouters import equipo_router
from .licenciaturaRouters import licenciatura_router
from .nivelRouter import nivel_router
from .dashboardRouters import asistencia_router