from .reservaAlumno1Schemas import ReservaAlumno1Schemas
from .reservaIdSchemas import ReservaIdShemas
from .reservaDeleteShemas import ReservaDeleteSchemas
from .estadoUsoUpdateSchema import EstadoUsoUpdateSchema
from .messageResponse import AsistenciaExitoSchema
from .messageResponse import ErrorSchema
from .reservaEquipoSchema import ReservaEquipoSchema
from .reservaAdmin1Schemas import ReservaAdmin1Schemas