from .reservaAlumnoCreateDTO import ReservaAlumnoCreateDTO
from .obtenerAgendaDTO import ObtenerAgendaDTO
from .reservaDeleteDTO import ReservaDeleteDTO
from .reservaDetailsDTO import ReservaDetailsDTO
from .EstadoUsoUpdateDTO import EstadoUsoUpdateDTO
from .reservaDTO import  ReservaDetalleDTO
from .asistenciaResponseDTO import AsistenciaResponseDTO
from .reservaEquipoDTO import ReservaEquipoDTO